# Generated by Django 3.2.8 on 2021-10-29 01:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nguoidung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dateofbirth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='RoomChat',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='nguoidung.roomchat'),
        ),
    ]
